name: Drupal
description: "Drupal is an open source content management platform supporting a variety of websites ranging from personal weblogs to large community-driven websites"
logo: https://unpkg.com/simple-icons@4.2.0/icons/drupal.svg
category: Content Management
source: https://github.com/drupal/drupal
contributors:
  - "orsvet"
versions:
  latest: deploy.yaml
