name: MongoDB
description: "MongoDB is a general purpose, document-based, distributed database built for modern application developers and for the cloud era"
logo: https://unpkg.com/simple-icons@4.2.0/icons/mongodb.svg
category: Databases
source: https://github.com/mongodb/mongo
contributors:
  - "davaymne"
versions:
  latest: deploy.yaml
