---
version: "2.0"

services:
  chia:
    image: cryptoandcoffee/akash-chia:60
    expose:
      - port: 8080
        as: 80
        proto: tcp
        to:
          - global: true
    env:
      - CONTRACT=
      - FARMERKEY=
      - REMOTE_LOCATION=local 
        #Choose local to access finished plots through web interface or upload finished plots to SSH destination path like /root/plots
      - PLOTTER=madmax
        #Choose your plotter software - madmax or blade (testnet only)
###################################################################
# Remote Upload Variables / Only enable if REMOTE_LOCATION != local
#      - REMOTE_HOST=changeme.com #SSH upload host
#      - REMOTE_LOCATION=changeme #SSH upload location like /root/plots
#      - REMOTE_PORT=22 #SSH upload port
#      - REMOTE_USER=changeme #SSH upload user
#      - REMOTE_PASS=changme #SSH upload password
profiles:
  compute:
    chia:
      resources:
        cpu:
          units: 10.0
        memory:
          size: 6Gi
#Chia blockchain is currently ~40gb as of November 2021 / if you are plotting please use at least 256Gi
        storage:
          size: 256Gi
  placement:
    akash:
      pricing:
        chia:
          denom: uakt
          amount: 1000
deployment:
  chia:
    akash:
      profile: chia
      count: 1
